version: '3.7'

services:
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    container_name: nance-redis

  postgres:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    container_name: nance-postgres
    environment:
      - POSTGRES_USER=nance
      - POSTGRES_PASSWORD=nance
      - POSTGRES_DB=nance
